- name: Install MLPerf Storage v2.0
  hosts: clients
  become: true
  tasks:
    - name: COMMON | Ensure curl, git and python build dependencies are installed
      ansible.builtin.package:
        name:
          - curl
          - git
        state: present

    - name: Download UV installer
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        dest: /tmp/install.sh
        mode: '0755'

    - name: Install UV
      ansible.builtin.command: "sh /tmp/install.sh"

    - name: Remove existing storage directory
      ansible.builtin.file:
        path: /root/storage
        state: absent

    - name: Clone MLPerf Storage Repository
      ansible.builtin.git:
        repo: https://github.com/mlcommons/storage.git
        dest: /root/storage
        version: main

    - name: Create and activate Python virtual environment
      ansible.builtin.command: /root/.local/bin/uv venv --python 3.12 /root/storage/.venv

    - name: Install OS-specific system dependencies (Debian)
      when: ansible_os_family == 'Debian'
      block:
        - name: Install Python and MPI packages
          ansible.builtin.package:
            name:
              - python3-dev
              - mpich
            state: present

    - name: Install OS-specific system dependencies (RedHat)
      when: ansible_os_family == 'RedHat'
      block:
        - name: Install Python and MPI packages
          ansible.builtin.package:
            name:
              - python3-devel
              - mpich
              - mpich-devel
            state: present

        - name: Export MPI paths
          shell: |
            echo 'export LD_LIBRARY_PATH=/usr/lib64/mpich/lib:$LD_LIBRARY_PATH' >> /root/.bashrc
            echo 'export PATH=/usr/lib64/mpich/bin:$PATH' >> /root/.bashrc
          args:
            executable: /bin/bash

    - name: Install OS-specific system dependencies (Suse)
      when: ansible_os_family == 'Suse'
      block:
        - name: Install base system packages
          ansible.builtin.package:
            name:
              - python3-devel
              - mpich
              - mpich-devel
              - gcc12
              - gcc12-c++
              - cpp12
            state: present

        - name: Export MPI paths
          shell: |
            echo 'export PATH=/usr/lib64/mpi/gcc/mpich/bin:$PATH' >> /root/.bashrc
            echo 'export LD_LIBRARY_PATH=/usr/lib64/mpi/gcc/mpich/lib64:$LD_LIBRARY_PATH' >> /root/.bashrc
            echo 'export CC=/usr/lib64/mpi/gcc/mpich/bin/mpicc' >> /root/.bashrc
          args:
            executable: /bin/bash

        - name: Set GCC 12 as default
          community.general.alternatives:
            name: "{{ item.name }}"
            link: "{{ item.link }}"
            path: "{{ item.path }}"
            priority: 80
          loop:
            - { name: gcc, link: /usr/bin/gcc, path: "/usr/bin/gcc-12" }
            - { name: g++, link: /usr/bin/g++, path: "/usr/bin/g++-12" }
            - { name: cpp, link: /usr/bin/cpp, path: "/usr/bin/cpp-12" }
            - { name: c++, link: /usr/bin/c++, path: "/usr/bin/g++-12" }

    - name: Install DLIO python requirements
      ansible.builtin.command: /root/.local/bin/uv pip install .
      args:
        chdir: /root/storage
      environment:
        CMAKE_POLICY_VERSION_MINIMUM: "3.5"